from .terrestrial import ITerrestrial
from .animal.freshwater import IFreshwater
from .aquatic import IAquatic
from .flying import IFlying
from .walking import IWalking
from .swimming import ISwimming
from .identifiable import Identifiable
from .habitat.contains_animals import IContainsAnimals
from .habitat.contains_plants import IContainsPlants
