from .organism.terrestrial import ITerrestrial
from .organism.aquatic import IAquatic
from .organism.freshwater import IFreshwater
from .organism.saltwater import ISaltwater
from .organism.animal.flying import IFlying
from .organism.animal.walking import IWalking
from .organism.animal.swimming import ISwimming
from .identifiable import Identifiable
from .habitat.contains_animals import IContainsAnimals
from .habitat.contains_plants import IContainsPlants
